[book]
authors = ["AaronWu-train"]
language = "zh-TW"
multilingual = false
src = "src"
title = "Ckefgisc Server Book"
description = "A passed down book about Ckefgisc's Server and Sites and its usage."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
git-repository-url = "https://github.com/CKEFGISC/server-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/CKEFGISC/server-book/edit/main/{path}"
cname = "serverbook.ckefgisc.org"
